### ISSUE TITLE
cyrillic set

### ISSUE THREAD

**Issue by renatlb** [RichardSepsi/Unageo#2]
Thank you very much for great work!
To note: cyrillic has two types - Bulgarian cyrillic and general cyrillic (Ukraine, Russian and many others).
Your font contains Bulgarian cyrillic set, so its usage would be limited mostly by Bulgarians. 
General Cyrillic slightly different (check letters "k" as example)

**Comment by RichardSepsi** [comment]
Thank you.
I am aware that cyrillic has two types and I specifically chose bulgarian, because it's more readable. 
However I don't think that the usage would be limited to Bulgarians as the style is very similar to general cyrillic when it's in crusive/alternate form.
![Screenshot_1](https://github.com/RichardSepsi/Unageo/assets/52209860/16ca454e-2b1a-4d2d-bb94-93576a6f5a4c)
