### ISSUE TITLE
Cyrillic Letters Shcha and Cyrillic Letters Tse (uni0446) | Broken Tails

### ISSUE THREAD

**Issue by StefanPeev** [RichardSepsi/Unageo#5]
The tail curves on Cyrillic Small Letter Shcha (uni0449) and Cyrillic Small Letter Tse (uni0446) are broken. See the pictures.

![Screenshot 2024-06-03 172924](https://github.com/RichardSepsi/Unageo/assets/12949369/ee852ea8-58cd-4b2c-8303-ccb2208c33b1)
![Screenshot 2024-06-03 172941](https://github.com/RichardSepsi/Unageo/assets/12949369/fbb45354-5274-402d-a15e-e7712f8fd364)

The highness of the tail in Cyrillic uppercase Ц and Щ needs to be the same as the horizontal bar in these letters. See the picture.

![Screenshot 2024-06-03 174352](https://github.com/RichardSepsi/Unageo/assets/12949369/8f7a356a-1c3c-4610-8e63-8f3ba1d7db9c)

**Comment by RichardSepsi** [comment]
Thank you for your input.
The first issue you mentioned is that the curve leading to the tail looks broken if understand it correctly.
That is intentional and part of the style.
However you are right with the tail height, that it should be the same as the horizontal bar and I will work on fixing it for the next update.
Those unnecessary nodes you mentioned are propably caused by conversion from quadratic to cubic splines. I'm not sure If I can do anything about that, but I'll see.
